version: "3"
services:
  redis:
    build: ./redis
    networks:
      - backend
    volumes:
      - ./data:/data
    restart: unless-stopped
  nginx:
    build: ./nginx_local
    networks:
      - backend
    ports:
      - "60:80"
    restart: unless-stopped
  gscal:
    build: ./gscal
    depends_on:
      - redis
      - nginx
    networks:
      - backend
    restart: unless-stopped
  home:
    build: ./home
    depends_on:
      - nginx
      - gscal
    networks:
      - backend
    restart: unless-stopped
networks:
  backend: